'use client'
import "./globals.css";
import StyledComponentsRegistry from "@/lib/registry";
import NavBar from "./components/layout/navbar/navbar";


// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>        
        <StyledComponentsRegistry>
          <NavBar />
          <main>
            {children}
          </main>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
